### ISSUE TITLE
File not found when import SpringBoard

### ISSUE THREAD

**Issue by duongvanthai** [hbang/SwitchSpring#3]
Hi, I'm newbie in Jailbreak tweak. When I copy SpringBoard header (iOS8.1) folder to $theos/include for build this project. But It's always has issue "file not found". 

Example when I import:
# import  "SpringBoard/SpringBoard.h"

It's has error: /opt/theos/include/SpringBoard/SpringBoard.h:7:9: 'FBSystemApp.h' file not found. But FBSystemApp is in PrivateFrameworks/FontBoard...

How to I fix it?

**Comment by kirb** [comment]
You are using dumped headers - these aren't meant for use by a compiler unless you clean them up. They're best as a reference, so then you can use the information to create your own working headers. The headers I use are at https://github.com/hbang/headers; you should rename your current include directory and clone this in its place.

**Comment by duongvanthai** [comment]
It's work. Thanks a lot. :+1:
